# Generated by Django 4.0.5 on 2022-08-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile'),
        ),
    ]
