# Generated by Django 4.0.5 on 2022-08-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0005_avatar_delete_profilepic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
