# Generated by Django 4.0.5 on 2022-08-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
