# Generated by Django 4.0.5 on 2022-07-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='resumen',
        ),
    ]
