# Generated by Django 4.0.5 on 2022-07-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub',
            field=models.CharField(default='', max_length=255),
        ),
    ]
