# Generated by Django 4.0.5 on 2022-07-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sub',
        ),
    ]
