# Generated by Django 4.0.5 on 2022-08-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
