# Generated by Django 4.0.5 on 2022-08-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
