# Generated by Django 4.0.5 on 2022-08-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_body'),
        ('blog', '0011_delete_avatar'),
    ]

    operations = [
    ]
